(#27)(#39)(#46)(#45) Rework and update the repository
chocolatey-community/chocolatey-packages-template pull request #47
Opened 2024-01-11 04:53 UTC by TheCakeIsNaOH

This is a major rework and update of the files in the repository. This removes ketarin references, switches au to chocolatey-au, and updates the scripts based on updates to the the majkinetor and chocolatey-community/chocolatey-packages repositories.

Fixes #27
Fixes #39
Fixes #45 
Fixes #46

2024-01-12 17:35 UTC, pauby reviewed
These are minor corrections.

This all looks good to me. I can't comments on the appveyor scripts / yml file without running it. But at a glance it looks fine.

Thats for doing all this work @TheCakeIsNaOH

2024-01-12 17:35 UTC, pauby commented on setup/README.md
> +* Run PowerShell `5.x` as Administrator (chocolatey-au framework supports PowerShell 6+ but this setup does not)
```suggestion
* Run PowerShell `5.x` as Administrator (chocolatey-au framework supports PowerShell 6+ but this setup does not).
```

2024-01-12 17:35 UTC, pauby commented on setup/README.md
> +* For local automatic packaging, copy update_vars_default.ps1 to update_default.ps1 and fill it in.
```suggestion
* For local automatic packaging, copy `update_vars_default.ps1` to `update_default.ps1` and fill it in.
```

2024-02-18 15:36 UTC, AdmiringWorm commented on .appveyor.yml
> +image: Visual Studio 2022
If I recall correctly, we never upgraded to above 2017 in the chocolatey core team packages repository, as we were seeing performance issues when using a later image (which caused build timeouts).

It might be best for now to stay with a known good value (Visual Studio 2017 is the one I know that is a good value).

2024-02-18 23:28 UTC, TheCakeIsNaOH commented on .appveyor.yml
> +image: Visual Studio 2022
I've been using 2022 on my repository, and build speeds have been fine.

I'm not finding any obvious issues/PRs on the chocolatey-community/chocolatey-packages repository discussing it, is there still information about what was slow on it? I'm not opposed to the change, it just would be good to have some information on why that is the version to use.

2024-02-19 09:19 UTC, AdmiringWorm commented on .appveyor.yml
> +image: Visual Studio 2022
It was back when we were still using Gitter, I don't think there were any discussions done in an issue or PR.

It may have been that it was the `Visual Studio 2019` causing problems.

If there are no longer any problems, I have no objection to the change.

2024-02-20 05:32 UTC, TheCakeIsNaOH commented on .appveyor.yml
> +image: Visual Studio 2022
> It was back when we were still using Gitter, I don't think there were any discussions done in an issue or PR.

Yup, I looked at my gitter export, and there was some discussion about it. 

Apparently `Visual Studio 2019` only had PowerShell core enabled at the time, so it was not possible to run AU on it. That was fixed (or was incorrect documentation), and all current images now have Windows PowerShell v5.1 as per: https://www.appveyor.com/docs/windows-images-software/#powershell

So I think that `Visual Studio 2022` can be used without issue.

2024-02-20 13:11 UTC, AdmiringWorm reviewed
The changes LGTM, and it looks like most of the changes are similar to what is being used in https://github.com/chocolatey-community/chocolatey-packages. Before I put a final approval from me, though, I would like to test out the image used in the AppVeyor script in the above mentioned repository.

I'll schedule some time next week to make those changes in that repository and come back to this PR afterward.

2024-07-12 06:09 UTC, JPRuskin commented on .appveyor.yml
> +    git clone -q https://github.com//chocolatey-community/chocolatey-au.git $Env:TEMP/au
```suggestion
    git clone -q https://github.com/chocolatey-community/chocolatey-au.git $Env:TEMP/au
```

2024-07-12 06:09 UTC, JPRuskin commented on .appveyor.yml
> +
```suggestion

```

2024-07-12 06:11 UTC, JPRuskin commented on .appveyor.yml
> +                    popd
Is it worth hardening this a little, i.e. to ensure we end up back out of the $package_dir?

```suggestion
                    try {
                      pushd $package_dir
                      if (Test-Path update.ps1 -ea 0) { ./update.ps1 }
                      choco pack
                      Push-Package
                    } finally {
                      popd
                    }
```

2024-07-13 14:59 UTC, TheCakeIsNaOH commented on .appveyor.yml
> +    git clone -q https://github.com//chocolatey-community/chocolatey-au.git $Env:TEMP/au
Fixed

2024-07-13 14:59 UTC, TheCakeIsNaOH commented on .appveyor.yml
> +
Fixed

2024-07-13 15:00 UTC, TheCakeIsNaOH commented on update_all.ps1
> +      'Could not establish trust relationship'              # -||-
I think it is a shrug, I removed it as it does not add documentation value.

2024-07-13 15:00 UTC, TheCakeIsNaOH commented on .appveyor.yml
> +                    popd
I've added this, it seems like a good idea.

2024-07-17 12:08 UTC, JPRuskin approved these changes
I think this looks good to me (two minor comments) - but I think it's still waiting on testing of the AppVeyor changes.

2024-07-17 12:08 UTC, JPRuskin commented on test_all.ps1
> +        'Could not establish trust relationship'              # -||-
```suggestion
        'Could not establish trust relationship'
```

Sorry, spotted this replication of the possibly-shrug comment - worth removing!

2024-07-18 02:35 UTC, TheCakeIsNaOH commented on setup/au_setup.ps1
> +# choco install chocolatey-au -y
Good catch, fixed.

2024-07-18 02:35 UTC, TheCakeIsNaOH commented on test_all.ps1
> +        'Could not establish trust relationship'              # -||-
Removed

2024-09-22 19:28 UTC, Jaykul commented
@JPRuskin @TheCakeIsNaOH what are we waiting for?
I just about went and started on this work myself, before I saw the PR ;-)

2024-09-23 00:08 UTC, TheCakeIsNaOH commented
@Jaykul I'm waiting for review on this PR, it should be someone else that approves and merges this (or asks for changes).

2024-09-30 12:01 UTC, pauby commented
@AdmiringWorm have you [looked at the appveyor changes](https://github.com/chocolatey-community/chocolatey-packages-template/pull/47#pullrequestreview-1890395135)?

2025-05-12 10:42 UTC, AdmiringWorm requested changes
Thanks for putting all of this together @TheCakeIsNaOH, and appologies for taking so long to review and test out the changes.

I've incorporated the changes in the main chocolatey-packages repository, and as part of this I noticed there were a few things that needs to be changed, or we should change.

2025-05-13 00:01 UTC, TheCakeIsNaOH commented on .appveyor.yml
> -  au_version:
Updated.

2025-05-13 00:01 UTC, TheCakeIsNaOH commented on .appveyor.yml
> +#      'autohotkey.install' = 'VERSION_HERE'
Updated.

2025-05-13 00:01 UTC, TheCakeIsNaOH commented on .appveyor.yml
>      . "$Env:TEMP/au/scripts/Install-AU.ps1" $Env:au_version
Updated.

2025-05-13 00:01 UTC, TheCakeIsNaOH commented on test_all.ps1
> +if ($ThrowOnErrors -and $au_errors.Count -gt 0) {
Updated.

2025-05-13 00:01 UTC, TheCakeIsNaOH commented on update_all.ps1
> +param([string[]] $Name, [string] $ForcedPackages, $Root = "$PSScriptRoot\automatic")
Updated.

2025-05-13 08:53 UTC, AdmiringWorm approved these changes
LGTM

2025-05-13 08:54 UTC, merged